export const DummyData = [
    {
        id:"elonmusk",
        name:"Elon Musk",
        verified:true,
        tweet:"Holding off relaunch of Blue Verified until there is high confidence of stopping impersonation. Will probably use different color check for organizations than individuals.",
        image:null,
        prof:"https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
        like:"232K",
        rt:"25.6K",
        reply:"25.6K",
        time:"2h",
    },
    {
        id:"ykdojo",
        name:"YK aka CS Dojo",
        tweet:"Never do something based on FOMO or peer pressure. Instead, figure out what you want to achieve, and then how exactly to get there.",
        verified:false,
        image:null,
        prof:"https://pbs.twimg.com/profile_images/1376825810900819968/RPtw5WuB_400x400.jpg",
        like:"20K",
        rt:"120",
        reply:"10",
        time:"5h",
    },
    {
        id:"MrRichee_",
        name:"Mr Richie",
        tweet:"Won 2 Gold medals at National Vovinam championship which held at Jalandhar. Punjab from 17th June to 20th June representing Tamilnadu  🚀⚡",
        verified:true,
        image:"https://pbs.twimg.com/media/FV5x1wYUYAAZ5iL?format=jpg&name=small",
        prof:"https://pbs.twimg.com/profile_images/1517962497524834304/YITGkv1y_400x400.jpg",
        like:"1M",
        rt:"67.9K",
        reply:"20.1K",
        time:"2d",
    },
    {
        id:"Cobratate",
        name:"Andrew Tate",
        tweet:
        "Good always triumphs over evil.",
        image:"https://pbs.twimg.com/media/FiLTcPmXgAMlTeB?format=jpg&name=small",
        verified:false,
        prof:"https://pbs.twimg.com/profile_images/1593669202702999554/aQ7YTs2C_400x400.jpg",
        like:"2M",
        rt:"121.4K",
        reply:"20.3K",
        time:"6d",
    },
    {
        id:"",
        name:"",
        tweet:"",
        image:"",
        prof:"",
        like:"",
        rt:"",
        reply:"",
    },
    {
        id:"",
        name:"",
        tweet:"",
        image:"",
        prof:"",
        like:"",
        rt:"",
        reply:"",
    },
    {
        id:"",
        name:"",
        tweet:"",
        image:"",
        prof:"",
        like:"",
        rt:"",
        reply:"",
    },
    
]